/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ChildComponent: typeof import('./src/components/ChildComponent.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewEditableTabs: typeof import('./src/components/NewEditableTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleComponent: typeof import('./src/components/SimpleComponent.vue')['default']
    SimpleTabs: typeof import('./src/components/SimpleTabs.vue')['default']
    Tab1: typeof import('./src/components/Tab1.vue')['default']
    Tab2: typeof import('./src/components/Tab2.vue')['default']
    Tab3: typeof import('./src/components/Tab3.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
